export const USER_ROLES = {
  CIRCUIT_COORDINATOR: "CIRCUIT_COORDINATOR",
  CIRCUIT_ASSISTANT: "CIRCUIT_ASSISTANT",
  CONGREGATION_COORDINATOR: "CONGREGATION_COORDINATOR",
  CONGREGATION_ASSISTANT: "CONGREGATION_ASSISTANT",
} as const;

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];
